version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.0
    steps:
      - checkout
      # - node/install-packages:
      #     pkg-manager: npm
      - run:
          command: npm install
          name: Install packages
      - run:
          command: npx hardhat test
          name: Run tests

workflows:
  build-test-dont-deploy:
    jobs:
      - build-and-test
