name: Upload ABI CI

on:
  push
#   pull_request:
#     branches:
#       - main
#       - deployment-scripts
#       - abiapi-yo
#     types: [closed]

env:
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    # if: github.event.pull_request.merged == true
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.gcp_credentials }}'

    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: 'README.md'
        destination: 'abiapi/README.md'
