name: Upload ABI CI

on:
  - push
  # pull_request:
  #   branches:
  #     - master
  #   types: [closed]

env:
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}

jobs:
  upload:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm ci && npx hardhat compile && mkdir ibco && cp artifacts/contracts/**/**/*.json ibco/
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.gcp_credentials }}'

    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: 'ibco'
        destination: 'abiapi/'
